name: bluzelle_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bech32: ^0.2.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  convert: ^3.0.0
  equatable: ^2.0.3
  fixnum: ^1.0.0
  json_annotation: ^4.0.1
  json_rpc_2: ^3.0.1
  pointycastle: ^3.1.3
  protobuf: ^2.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.5
  import_sorter: ^4.6.0
  json_serializable: ^4.1.3
  lints: ^1.0.1
  test: ^1.16.0

import_sorter:
  ignored_files:
    - codec\/*
